[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "Unicode-3.0",
]

[licenses.private]
ignore = true

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[bans]
multiple-versions = "warn"
wildcards = "deny"
