blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/astral-sh/cfgcut/security/policy
    about: Please follow our security policy for reporting vulnerabilities.
