name: Zizmor

on:
  pull_request:
  push:
    branches: [main, master]

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@a166459515afca5fef65cc68068d8cc6c0b0b17a # v0.5.5
        with:
          advanced-security: false
          config: .github/zizmor.yml
          min-severity: medium
